# Generated by Django 5.0 on 2023-12-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='referalID',
        ),
    ]
