# Generated by Django 5.0 on 2023-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
