# Generated by Django 5.0.1 on 2024-01-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_products',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
