# Generated by Django 5.0.1 on 2024-01-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('Regular Delivery', 'Regular Delivery'), ('Instant Delivery', 'Instant Delivery')], null=True),
        ),
    ]
