# Generated by Django 5.0 on 2023-12-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_users_referalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='lastOTP',
        ),
        migrations.RemoveField(
            model_name='users',
            name='otpSent',
        ),
    ]
