# Generated by Django 5.0.1 on 2024-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_orders_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'Online Payment'), ('Card', 'Credit/Debit Card'), ('EMI', 'EMI')]),
        ),
    ]
