# Generated by Django 5.0 on 2023-12-28 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cart'),
        ),
    ]
