# Generated by Django 5.0 on 2023-12-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_delete_login_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.TextField(),
        ),
    ]
