# Generated by Django 5.0.1 on 2024-01-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
