# Generated by Django 5.0 on 2023-12-15 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_products_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
