# Generated by Django 5.0 on 2023-12-15 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
